### ISSUE TITLE
Please consider renaming bltVector.h to tkBLTVector.h

### ISSUE THREAD

**Issue by olebole** [wjoye/tkblt#1]
I just started to create a Debian package for tkBLT. One problem that arises here (seems to be the only problem ;-) however) is that tkBLT installs a file `/usr/include/bltVector.h`. This file conflicts with a file from the "conventional" BLT package, so that one cannot install both at the same time.

Would it be possible to rename it to `/usr/include/tkBLTVector.h` or similar? I could do this also locally in the Debian package, but having the same name everywhere would increase consistency and the possibility of coexistence with BLT.

If needed, I can provide a patch.

Best regards

Ole

**Comment by wjoye** [comment]
Good point. All filenames have been changed to avoid conflict with older versions of blt.
