### ISSUE TITLE
Build problems with gcc 6

### ISSUE THREAD

**Issue by olebole** [wjoye/tkblt#4]
On Debian, there was recently a rebuild with the latest gcc version, which failed for tkblt:

```
gcc -DPACKAGE_NAME=\"tkblt\" [...]  -g -O2 -fstack-protector-strong \
 -Wformat -Werror=format-security -pipe -fomit-frame-pointer \
 -DNDEBUG -Wall -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 \
 -c `echo src/tkbltVecMath.C` -o src/tkbltVecMath.o
src/tkbltVecMath.C:1483:48: error: overloaded function with no contextual type information
     {"acos", (void*)ComponentFunc, (ClientData)acos},
                                                ^~~~
src/tkbltVecMath.C:1484:48: error: overloaded function with no contextual type information
     {"asin", (void*)ComponentFunc, (ClientData)asin},
                                                ^~~~
[...]
```

Full log [here](http://people.debian.org/~lucas/logs/2016/07/13/tkblt_3.2.1-2_unstable_gcc6.log).
This is reported as [Debian bug #831167](https://bugs.debian.org/831167).

**Comment by wjoye** [comment]
added global namespace spec to generic math functions

**Comment by olebole** [comment]
Thank you very much! I'll upload the new version to Debian tomorrow.

**Comment by mobarre** [comment]
Hi !

Sorry to barge in a closed ticket, but I seem to be getting the same issue with gcc 6.1.1 and a git clone of the repo with the fix from 4 days ago. Am I missing something ?

[build.txt](https://github.com/SAOImageDS9/tkblt/files/369248/build.txt)

**Comment by wjoye** [comment]
yep, still a problem. Working on it.

**Comment by wjoye** [comment]
fixed.

**Comment by gronki** [comment]
When will this be pulled to ds9?

**Comment by wjoye** [comment]
Sorry for the delay, tkblt has been updated in ds9

**Comment by wjoye** [comment]
fixed

**Comment by opoplawski** [comment]
Could we get a new ds9 release with these fixes?

**Comment by deliazhang** [comment]
I am still getting this error
