### ISSUE TITLE
Failed to build on Windows

### ISSUE THREAD

**Issue by yyamasak** [wjoye/tkblt#5]
I tried to build tkblt 3.2.2 on Windows 7 SP1 64bit. But make command failed (probably at linker step.)
I used MinGW gcc 4.9.3 (not MinGW2). Could you have a look at my log file?

$ gcc --version
gcc.exe (GCC) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ ./configure --enable-threads --with-tcl=/c/src/tcl8.6.5/win --with-tk=/c/src/tk8.6.5/win --prefix=/c/bin/tcl8.6.5
$ make all 1> make.txt 2>&1

[make.txt](https://github.com/SAOImageDS9/tkblt/files/369043/make.txt)

**Comment by wjoye** [comment]
yes, known problem. working on it now. stay tuned.

**Comment by yyamasak** [comment]
Thank you! I appreciate for your amazing work for the revival of BLT.

**Comment by wjoye** [comment]
Fixed

**Comment by wjoye** [comment]
Oops, still broken. I'll need to look into this in detail

**Comment by yyamasak** [comment]
JFYI.
I tried to build tkblt-3.2.6 with gcc 6.3.0 of the latest MSYS2 32bit on Windows 7 32bit.
Basically, no change except for -static-libgcc option given to the linker.
[make.txt](https://github.com/wjoye/tkblt/files/1051115/make.txt)

**Comment by yyamasak** [comment]
I could successfully build 3.2.7. However, it lacks Blt_Init entry point.
Still it doesn't work on Windows. Also I think pkgIndex.tcl must be corrected.
```tcl
# pkgIndex.tcl
package ifneeded tkblt 3.2 \
    [list load [file join $dir tkblt32.dll] Blt]
```
```dos
C:\bin\tcl8.6.6\lib\tkblt3.2>dumpbin /EXPORTS tkblt32.dll
Microsoft (R) COFF/PE Dumper Version 14.10.25019.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file tkblt32.dll

File Type: DLL

  Section contains the following exports for tkblt32.dll

    00000000 characteristics
    598A7346 time date stamp Wed Aug  9 11:28:22 2017
        0.00 version
           1 ordinal base
          20 number of functions
          20 number of names

    ordinal hint RVA      name

          1    0 00032C10 Blt_AllocVectorId = ___do_global_ctors
          2    1 00032910 Blt_CreateVector
          3    2 00032810 Blt_CreateVector2 = _Tk_InitStubs
          4    3 00032950 Blt_DeleteVector
          5    4 00032970 Blt_DeleteVectorByName
          6    5 00030300 Blt_ExprVector
          7    6 00032CC0 Blt_FreeVectorId
          8    7 00032A40 Blt_GetVector
          9    8 00032D30 Blt_GetVectorById
         10    9 00032AB0 Blt_GetVectorFromObj
         11    A 00032DB0 Blt_InstallIndexProc
         12    B 00032D20 Blt_NameOfVector
         13    C 00032D00 Blt_NameOfVectorId
         14    D 00032B30 Blt_ResetVector
         15    E 00032B80 Blt_ResizeVector
         16    F 00032CA0 Blt_SetVectorChangedProc
         17   10 0002DD10 Blt_VecMax
         18   11 0002DD20 Blt_VecMin
         19   12 00032A00 Blt_VectorExists
         20   13 000329D0 Blt_VectorExists2

  Summary

        1000 .CRT
        2000 .bss
        5000 .data
        1000 .edata
        D000 .eh_fram
        1000 .idata
        B000 .rdata
        4000 .reloc
       3E000 .text
        1000 .tls
```
